# Generated by Django 6.0 on 2025-12-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Absolute or relative path to the image file', max_length=500)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('checksum', models.CharField(help_text='SHA256 checksum for duplicate detection', max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='segmentation.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checksum'], name='segmentatio_checksu_42821c_idx')],
                'unique_together': {('dataset', 'checksum')},
            },
        ),
    ]
