# Generated by Django 6.0 on 2025-12-13 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_segmentationtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('SEGMENTER', 'Segmenter'), ('QC', 'Quality Control'), ('QA', 'Quality Assurance')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum active tasks allowed')),
                ('current_workload', models.PositiveIntegerField(default=0, help_text='Current active tasks count')),
                ('is_available', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='segmentation.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'role_in_project', 'current_workload'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
