# Generated by Django 6.0 on 2025-12-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_batch_batchimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationtask',
            name='feedback',
            field=models.TextField(blank=True, help_text='QA Feedback regarding rejection', null=True),
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('QC', 'Quality Control'), ('QA', 'Quality Assurance')], max_length=5)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECT_EDIT', 'Reject - Edit Required'), ('REJECT_REDO', 'Reject - Full Redo')], max_length=20)),
                ('comments', models.TextField(help_text='Mandatory explanation for decision')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='segmentation.segmentationtask')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
