# Generated by Django 6.0 on 2025-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0007_segmentationtask_feedback_taskreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreview',
            name='comments',
            field=models.TextField(blank=True, help_text='Mandatory explanation for decision', null=True),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='review_type',
            field=models.CharField(choices=[('QC', 'Quality Control'), ('QA', 'Quality Assurance')], default='QA', max_length=5),
        ),
    ]
