# Generated by Django 6.0 on 2025-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0008_alter_taskreview_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreview',
            name='duration',
            field=models.DurationField(blank=True, help_text='Time taken for review', null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When QA finished', null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When QA started', null=True),
        ),
    ]
